script: |
  if [ ! -d "Api-26/.git" ]; then
    rm -rf Api-26
    git clone https://github.com/ribeiroeletronic-ctrl/Api-26.git
  fi

  cd Api-26
  git pull origin main

  sudo docker stop minha-api || true
  sudo docker rm minha-api || true
  sudo docker build -t minha-api .
  sudo docker run -d -p 8000:8000 minha-api